### ISSUE TITLE
Centos 7 compatible? Standalone usage compatible?

### ISSUE THREAD

**Issue by Sispheor** [robertdebock/ansible-role-phpmyadmin#7]
Hi, I would like to use this role on Centos 7 server.
Also, is the musql role a mandatory dep? I have installed mariadb in a cluster with another playbook. I only need PMA.

Thanks.

**Comment by robertdebock** [comment]
I've added tests for CentOS-7. Now [building](https://travis-ci.org/robertdebock/ansible-role-phpmyadmin/builds/360274843).

Locally it seemed to work. I'll close when the build is successful, please let me know if you encounter other issues.

**Comment by Sispheor** [comment]
Yes it works. Thx
